const activities = [

    {
        title: "10-Minute Photo Scavenger Hunt",
        description: "Take your phone or camera and find 10 things around you: something red, something tiny, a reflection, an interesting texture, a shadow, something symmetrical, and four things of your choice.",
        interests: ["photography", "art", "creative"],
        moods: ["fun", "creative"],
        energy: ["low", "medium"],
        time: ["15min", "30min"],
        social: ["alone", "friends", "family"],
        location: ["home", "outside", "anywhere"],
        cost: ["free"],
        effort: ["low"],
        goals: ["fun_goal", "learning"],
        future: false,
        unexpected: false,
        duration: "10–20 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Easy"
    },

    {
        title: "One-Colour Photography Challenge",
        description: "Choose one colour and take 5–10 photos where that colour is the main focus. Look for objects, clothing, buildings, reflections, or nature.",
        interests: ["photography", "art", "creative"],
        moods: ["creative", "fun"],
        energy: ["low", "medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["outside", "anywhere"],
        cost: ["free"],
        effort: ["low", "medium"],
        goals: ["fun_goal", "learning"],
        future: false,
        unexpected: false,
        duration: "20–40 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Easy"
    },

    {
        title: "Tell a Story in 5 Photos",
        description: "Create a tiny visual story using only five photographs. Your story can be funny, mysterious, peaceful, dramatic, or completely random.",
        interests: ["photography", "art", "creative", "writing"],
        moods: ["creative", "fun"],
        energy: ["medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["home", "outside", "anywhere"],
        cost: ["free"],
        effort: ["medium"],
        goals: ["fun_goal", "learning", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "30–60 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Medium"
    },

    {
        title: "Create a $0 Business",
        description: "Invent a business you could start with $0. Choose a problem, create a product or service that solves it, name your business, decide who your customers are, and figure out how you would make money.",
        interests: ["business", "money", "creative", "technology"],
        moods: ["productive", "creative"],
        energy: ["medium", "high"],
        time: ["1hour", "afternoon"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free"],
        effort: ["medium", "high"],
        goals: ["money_goal", "future", "extracurricular", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "45–90 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Medium"
    },

    {
        title: "Design Your Dream Business",
        description: "Create the brand for an imaginary business. Choose its name, logo idea, colours, target customer, product, price, and slogan. You can make it digitally or on paper.",
        interests: ["business", "art", "creative", "fashion"],
        moods: ["creative", "productive"],
        energy: ["medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free"],
        effort: ["medium"],
        goals: ["fun_goal", "future", "extracurricular", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "30–60 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Medium"
    },

    {
        title: "Build a Mock Investment Portfolio",
        description: "Choose 5 real companies you are interested in and create a pretend $10,000 investment portfolio. Decide how much you would put into each and research why.",
        interests: ["business", "money", "learning", "technology"],
        moods: ["productive"],
        energy: ["medium"],
        time: ["1hour", "afternoon"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free"],
        effort: ["medium"],
        goals: ["learning", "future", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "45–90 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Medium"
    },

    {
        title: "Create a Teen Budget",
        description: "Imagine you receive $200 per month. Decide how much you would save, spend, donate, and keep for fun. Then see whether your budget actually works.",
        interests: ["money", "business", "learning"],
        moods: ["productive"],
        energy: ["low", "medium"],
        time: ["15min", "30min"],
        social: ["alone"],
        location: ["home"],
        cost: ["free"],
        effort: ["low"],
        goals: ["learning", "future", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "15–30 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Find 5 Problems Teenagers Have",
        description: "Write down five everyday problems teenagers experience. Then choose one and brainstorm as many possible products, apps, or services that could solve it.",
        interests: ["business", "technology", "creative"],
        moods: ["productive", "creative"],
        energy: ["medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["home", "anywhere"],
        cost: ["free"],
        effort: ["medium"],
        goals: ["learning", "future", "extracurricular"],
        future: true,
        unexpected: false,
        duration: "30–45 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Easy"
    },

    {
        title: "Make Your Own Quiz",
        description: "Create a 10-question quiz about something you love. It could be about movies, music, geography, fashion, sports, books, or literally anything.",
        interests: ["technology", "creative", "writing", "anything"],
        moods: ["fun", "creative", "productive"],
        energy: ["low", "medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free"],
        effort: ["medium"],
        goals: ["fun_goal", "learning", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "30–60 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Easy"
    },

    {
        title: "Design an App That Doesn't Exist",
        description: "Think of an annoying problem you have and design an app that would solve it. Give it a name, choose its features, sketch the screens, and explain how it would work.",
        interests: ["technology", "business", "art", "creative"],
        moods: ["creative", "productive"],
        energy: ["medium", "high"],
        time: ["1hour", "afternoon"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free"],
        effort: ["medium", "high"],
        goals: ["learning", "future", "extracurricular", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "45–90 min",
        costLabel: "Free",
        socialLabel: "Solo or with friends",
        difficulty: "Medium"
    },

    {
        title: "Random Wikipedia Adventure",
        description: "Open a random Wikipedia article. Read it for five minutes, choose something interesting from the article, and follow the rabbit hole. See where you end up after 30 minutes.",
        interests: ["learning", "science", "history", "anything"],
        moods: ["fun", "creative"],
        energy: ["low", "medium"],
        time: ["15min", "30min", "1hour"],
        social: ["alone"],
        location: ["home", "anywhere"],
        cost: ["free"],
        effort: ["low"],
        goals: ["fun_goal", "learning"],
        future: false,
        unexpected: true,
        duration: "15–30 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Learn 10 Words in a New Language",
        description: "Choose a language you've never studied and learn 10 useful words or phrases. Then try writing a tiny conversation using them.",
        interests: ["writing", "learning", "anything"],
        moods: ["productive", "fun"],
        energy: ["low", "medium"],
        time: ["15min", "30min"],
        social: ["alone", "friends"],
        location: ["home", "anywhere"],
        cost: ["free"],
        effort: ["low"],
        goals: ["learning", "future"],
        future: true,
        unexpected: true,
        duration: "15–30 min",
        costLabel: "Free",
        socialLabel: "Solo or with a friend",
        difficulty: "Easy"
    },

    {
        title: "Make a Vision Board for Your Future",
        description: "Create a digital or physical collage showing places you want to go, skills you want to learn, things you want to accomplish, and the kind of life you want to build.",
        interests: ["art", "creative", "fashion", "writing"],
        moods: ["creative", "relax"],
        energy: ["low", "medium"],
        time: ["30min", "1hour"],
        social: ["alone", "friends"],
        location: ["home"],
        cost: ["free", "cheap"],
        effort: ["low", "medium"],
        goals: ["future", "productive_goal", "relax_goal"],
        future: true,
        unexpected: false,
        duration: "30–60 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Redesign Your Room on Paper",
        description: "Sketch your room and experiment with a completely new layout. Move furniture around, choose a colour palette, and decide what you would change.",
        interests: ["art", "creative", "fashion"],
        moods: ["creative", "productive"],
        energy: ["low", "medium"],
        time: ["30min", "1hour"],
        social: ["alone", "family"],
        location: ["home"],
        cost: ["free"],
        effort: ["low", "medium"],
        goals: ["fun_goal", "productive_goal"],
        future: false,
        unexpected: false,
        duration: "30–60 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Create a 5-Song Mood Playlist",
        description: "Choose one very specific mood or situation and create a five-song playlist for it. Examples: rainy afternoon, main-character walk, late-night studying, or summer road trip.",
        interests: ["music", "creative"],
        moods: ["fun", "relax", "creative"],
        energy: ["low", "medium"],
        time: ["15min", "30min"],
        social: ["alone", "friends"],
        location: ["home", "anywhere"],
        cost: ["free"],
        effort: ["low"],
        goals: ["fun_goal", "relax_goal"],
        future: false,
        unexpected: false,
        duration: "15–30 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Try a Recipe You've Never Made",
        description: "Find a recipe you've never tried before and make it from scratch. Challenge yourself to choose something with at least one ingredient you've never cooked with.",
        interests: ["food", "creative"],
        moods: ["fun", "creative", "productive"],
        energy: ["medium", "high"],
        time: ["30min", "1hour", "afternoon"],
        social: ["alone", "friends", "family"],
        location: ["home"],
        cost: ["cheap", "money"],
        effort: ["medium"],
        goals: ["fun_goal", "learning"],
        future: false,
        unexpected: false,
        duration: "45–90 min",
        costLabel: "Low cost",
        socialLabel: "Solo or with others",
        difficulty: "Medium"
    },

    {
        title: "Go on a 30-Minute Photo Walk",
        description: "Take your camera or phone outside and walk somewhere familiar. Your goal is to photograph five things you've walked past before but never really noticed.",
        interests: ["photography", "nature", "creative"],
        moods: ["creative", "fun", "relax"],
        energy: ["medium", "high"],
        time: ["30min", "1hour"],
        social: ["alone", "friends", "family"],
        location: ["outside"],
        cost: ["free"],
        effort: ["low", "medium"],
        goals: ["fun_goal", "learning", "relax_goal"],
        future: false,
        unexpected: false,
        duration: "30–45 min",
        costLabel: "Free",
        socialLabel: "Solo or with others",
        difficulty: "Easy"
    },

    {
        title: "Make a Mini Documentary",
        description: "Choose something ordinary around you—a person, place, object, hobby, or routine—and create a 1–3 minute video telling its story.",
        interests: ["photography", "technology", "creative", "writing"],
        moods: ["creative", "productive"],
        energy: ["medium", "high"],
        time: ["1hour", "afternoon", "days"],
        social: ["alone", "friends", "family"],
        location: ["home", "outside", "anywhere"],
        cost: ["free"],
        effort: ["medium", "high"],
        goals: ["learning", "productive_goal", "future"],
        future: true,
        unexpected: true,
        duration: "1–3 hours",
        costLabel: "Free",
        socialLabel: "Solo or with others",
        difficulty: "Medium"
    },

    {
        title: "Start a 7-Day Skill Challenge",
        description: "Pick one tiny skill you've always wanted to learn and spend 15–30 minutes practicing it every day for one week. Keep track of what improves.",
        interests: ["learning", "technology", "art", "music", "fitness"],
        moods: ["productive"],
        energy: ["medium", "high"],
        time: ["30min", "days"],
        social: ["alone", "friends"],
        location: ["home", "anywhere"],
        cost: ["free"],
        effort: ["medium", "high"],
        goals: ["learning", "future", "productive_goal"],
        future: true,
        unexpected: false,
        duration: "15–30 min/day",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Medium"
    },

    {
        title: "Write a Letter to Your Future Self",
        description: "Write a letter to yourself one year from now. Talk about what you're doing now, what you're worried about, what you hope changes, and what you want future-you to remember.",
        interests: ["writing", "creative"],
        moods: ["relax", "productive"],
        energy: ["low"],
        time: ["15min", "30min"],
        social: ["alone"],
        location: ["home"],
        cost: ["free"],
        effort: ["low"],
        goals: ["future", "relax_goal"],
        future: true,
        unexpected: false,
        duration: "15–30 min",
        costLabel: "Free",
        socialLabel: "Solo",
        difficulty: "Easy"
    },

    {
        title: "Create Your Own Bingo Challenge",
        description: "Make a 5×5 bingo board filled with tiny activities you can complete this week. Include things you've been putting off, fun challenges, and completely random tasks.",
        interests: ["creative", "writing", "anything"],
        moods: ["fun", "productive", "creative"],
        energy: ["low", "medium", "high"],
        time: ["30min", "1hour", "days"],
        social: ["alone", "friends", "family"],
        location: ["home", "outside", "anywhere"],
        cost: ["free"],
        effort: ["low", "medium"],
        goals: ["fun_goal", "productive_goal"],
        future: false,
        unexpected: true,
        duration: "30–45 min to create",
        costLabel: "Free",
        socialLabel: "Solo or with others",
        difficulty: "Easy"
    }

];
